// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/chat.dart';
import 'api/conversation.dart';
import 'api/echo.dart';
import 'api/lifecycle.dart';
import 'api/message.dart';
import 'api/profile.dart';
import 'api/settings.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiEchoInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 772182160;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'quinhub_bridge',
        ioDirectory: '../core/crates/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiChatChatCancel({required String chatId});

  Stream<ChatEventDto> crateApiChatChatEditResend({
    required String chatId,
    required String conversationId,
    required String messageId,
    required String newText,
  });

  Stream<ChatEventDto> crateApiChatChatRegenerate({
    required String chatId,
    required String conversationId,
  });

  Stream<ChatEventDto> crateApiChatChatSend({
    required String chatId,
    required String conversationId,
    String? userText,
    required List<ImageInput> userImages,
  });

  Future<List<ConversationDto>> crateApiConversationConversationArchivedList();

  Future<ConversationDto> crateApiConversationConversationCreate({
    String? profileId,
    String? modelId,
  });

  Future<void> crateApiConversationConversationDelete({required String id});

  Future<ConversationDto> crateApiConversationConversationGet({
    required String id,
  });

  Future<List<ConversationDto>> crateApiConversationConversationList();

  Future<ConversationDto> crateApiConversationConversationSetModel({
    required String id,
    required String profileId,
    required String modelId,
  });

  Future<ConversationDto> crateApiConversationConversationUpdateMeta({
    required String id,
    String? title,
    bool? pinned,
    bool? archived,
  });

  Future<ConversationDto> crateApiConversationConversationUpdateParams({
    required String id,
    required String params,
  });

  Stream<String> crateApiEchoEchoStream({required String input});

  Future<void> crateApiEchoInitApp();

  Future<void> crateApiLifecycleInitCore({
    required String dbPath,
    required String masterKeyB64,
    required String appDir,
  });

  Future<void> crateApiMessageMessageDelete({required String id});

  Future<List<MessageDto>> crateApiMessageMessageList({
    required String conversationId,
  });

  Future<List<MessageDto>> crateApiMessageMessageListPage({
    required String conversationId,
    PlatformInt64? beforeCreatedAt,
    PlatformInt64? beforeRowid,
    required int limit,
  });

  Future<bool> crateApiProfileModelSupportsVision({required String modelId});

  Future<ProfileDto> crateApiProfileProfileCreate({
    required String name,
    required String providerType,
    required String baseUrl,
    required String apiKey,
    required bool isDefault,
  });

  Future<void> crateApiProfileProfileDelete({required String id});

  Future<ProfileDto> crateApiProfileProfileGet({required String id});

  Future<List<ProfileDto>> crateApiProfileProfileList();

  Future<List<String>> crateApiProfileProfileTest({required String id});

  Future<ProfileDto> crateApiProfileProfileUpdate({
    required String id,
    required String name,
    required String baseUrl,
    String? apiKey,
    required bool isDefault,
    required List<String> enabledModels,
  });

  Future<String?> crateApiSettingsSettingsGet({required String key});

  Future<void> crateApiSettingsSettingsSet({
    required String key,
    required String value,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiChatChatCancel({required String chatId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chatId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiChatChatCancelConstMeta,
        argValues: [chatId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChatChatCancelConstMeta =>
      const TaskConstMeta(debugName: "chat_cancel", argNames: ["chatId"]);

  @override
  Stream<ChatEventDto> crateApiChatChatEditResend({
    required String chatId,
    required String conversationId,
    required String messageId,
    required String newText,
  }) {
    final sink = RustStreamSink<ChatEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_chat_event_dto_Sse(sink, serializer);
            sse_encode_String(chatId, serializer);
            sse_encode_String(conversationId, serializer);
            sse_encode_String(messageId, serializer);
            sse_encode_String(newText, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiChatChatEditResendConstMeta,
          argValues: [sink, chatId, conversationId, messageId, newText],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiChatChatEditResendConstMeta => const TaskConstMeta(
    debugName: "chat_edit_resend",
    argNames: ["sink", "chatId", "conversationId", "messageId", "newText"],
  );

  @override
  Stream<ChatEventDto> crateApiChatChatRegenerate({
    required String chatId,
    required String conversationId,
  }) {
    final sink = RustStreamSink<ChatEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_chat_event_dto_Sse(sink, serializer);
            sse_encode_String(chatId, serializer);
            sse_encode_String(conversationId, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiChatChatRegenerateConstMeta,
          argValues: [sink, chatId, conversationId],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiChatChatRegenerateConstMeta => const TaskConstMeta(
    debugName: "chat_regenerate",
    argNames: ["sink", "chatId", "conversationId"],
  );

  @override
  Stream<ChatEventDto> crateApiChatChatSend({
    required String chatId,
    required String conversationId,
    String? userText,
    required List<ImageInput> userImages,
  }) {
    final sink = RustStreamSink<ChatEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_chat_event_dto_Sse(sink, serializer);
            sse_encode_String(chatId, serializer);
            sse_encode_String(conversationId, serializer);
            sse_encode_opt_String(userText, serializer);
            sse_encode_list_image_input(userImages, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 4,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiChatChatSendConstMeta,
          argValues: [sink, chatId, conversationId, userText, userImages],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiChatChatSendConstMeta => const TaskConstMeta(
    debugName: "chat_send",
    argNames: ["sink", "chatId", "conversationId", "userText", "userImages"],
  );

  @override
  Future<List<ConversationDto>> crateApiConversationConversationArchivedList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationArchivedListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationArchivedListConstMeta =>
      const TaskConstMeta(
        debugName: "conversation_archived_list",
        argNames: [],
      );

  @override
  Future<ConversationDto> crateApiConversationConversationCreate({
    String? profileId,
    String? modelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(profileId, serializer);
          sse_encode_opt_String(modelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_conversation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationCreateConstMeta,
        argValues: [profileId, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationCreateConstMeta =>
      const TaskConstMeta(
        debugName: "conversation_create",
        argNames: ["profileId", "modelId"],
      );

  @override
  Future<void> crateApiConversationConversationDelete({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationDeleteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationDeleteConstMeta =>
      const TaskConstMeta(debugName: "conversation_delete", argNames: ["id"]);

  @override
  Future<ConversationDto> crateApiConversationConversationGet({
    required String id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_conversation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationGetConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationGetConstMeta =>
      const TaskConstMeta(debugName: "conversation_get", argNames: ["id"]);

  @override
  Future<List<ConversationDto>> crateApiConversationConversationList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_conversation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationListConstMeta =>
      const TaskConstMeta(debugName: "conversation_list", argNames: []);

  @override
  Future<ConversationDto> crateApiConversationConversationSetModel({
    required String id,
    required String profileId,
    required String modelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(profileId, serializer);
          sse_encode_String(modelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_conversation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationSetModelConstMeta,
        argValues: [id, profileId, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationSetModelConstMeta =>
      const TaskConstMeta(
        debugName: "conversation_set_model",
        argNames: ["id", "profileId", "modelId"],
      );

  @override
  Future<ConversationDto> crateApiConversationConversationUpdateMeta({
    required String id,
    String? title,
    bool? pinned,
    bool? archived,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_opt_String(title, serializer);
          sse_encode_opt_box_autoadd_bool(pinned, serializer);
          sse_encode_opt_box_autoadd_bool(archived, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_conversation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationUpdateMetaConstMeta,
        argValues: [id, title, pinned, archived],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationUpdateMetaConstMeta =>
      const TaskConstMeta(
        debugName: "conversation_update_meta",
        argNames: ["id", "title", "pinned", "archived"],
      );

  @override
  Future<ConversationDto> crateApiConversationConversationUpdateParams({
    required String id,
    required String params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_conversation_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiConversationConversationUpdateParamsConstMeta,
        argValues: [id, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConversationConversationUpdateParamsConstMeta =>
      const TaskConstMeta(
        debugName: "conversation_update_params",
        argNames: ["id", "params"],
      );

  @override
  Stream<String> crateApiEchoEchoStream({required String input}) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            sse_encode_String(input, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 13,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiEchoEchoStreamConstMeta,
          argValues: [sink, input],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEchoEchoStreamConstMeta => const TaskConstMeta(
    debugName: "echo_stream",
    argNames: ["sink", "input"],
  );

  @override
  Future<void> crateApiEchoInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEchoInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEchoInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiLifecycleInitCore({
    required String dbPath,
    required String masterKeyB64,
    required String appDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(masterKeyB64, serializer);
          sse_encode_String(appDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiLifecycleInitCoreConstMeta,
        argValues: [dbPath, masterKeyB64, appDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLifecycleInitCoreConstMeta => const TaskConstMeta(
    debugName: "init_core",
    argNames: ["dbPath", "masterKeyB64", "appDir"],
  );

  @override
  Future<void> crateApiMessageMessageDelete({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiMessageMessageDeleteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessageMessageDeleteConstMeta =>
      const TaskConstMeta(debugName: "message_delete", argNames: ["id"]);

  @override
  Future<List<MessageDto>> crateApiMessageMessageList({
    required String conversationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(conversationId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiMessageMessageListConstMeta,
        argValues: [conversationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessageMessageListConstMeta => const TaskConstMeta(
    debugName: "message_list",
    argNames: ["conversationId"],
  );

  @override
  Future<List<MessageDto>> crateApiMessageMessageListPage({
    required String conversationId,
    PlatformInt64? beforeCreatedAt,
    PlatformInt64? beforeRowid,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(conversationId, serializer);
          sse_encode_opt_box_autoadd_i_64(beforeCreatedAt, serializer);
          sse_encode_opt_box_autoadd_i_64(beforeRowid, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiMessageMessageListPageConstMeta,
        argValues: [conversationId, beforeCreatedAt, beforeRowid, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessageMessageListPageConstMeta =>
      const TaskConstMeta(
        debugName: "message_list_page",
        argNames: ["conversationId", "beforeCreatedAt", "beforeRowid", "limit"],
      );

  @override
  Future<bool> crateApiProfileModelSupportsVision({required String modelId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProfileModelSupportsVisionConstMeta,
        argValues: [modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileModelSupportsVisionConstMeta =>
      const TaskConstMeta(
        debugName: "model_supports_vision",
        argNames: ["modelId"],
      );

  @override
  Future<ProfileDto> crateApiProfileProfileCreate({
    required String name,
    required String providerType,
    required String baseUrl,
    required String apiKey,
    required bool isDefault,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_String(providerType, serializer);
          sse_encode_String(baseUrl, serializer);
          sse_encode_String(apiKey, serializer);
          sse_encode_bool(isDefault, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiProfileProfileCreateConstMeta,
        argValues: [name, providerType, baseUrl, apiKey, isDefault],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileCreateConstMeta =>
      const TaskConstMeta(
        debugName: "profile_create",
        argNames: ["name", "providerType", "baseUrl", "apiKey", "isDefault"],
      );

  @override
  Future<void> crateApiProfileProfileDelete({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiProfileProfileDeleteConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileDeleteConstMeta =>
      const TaskConstMeta(debugName: "profile_delete", argNames: ["id"]);

  @override
  Future<ProfileDto> crateApiProfileProfileGet({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiProfileProfileGetConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileGetConstMeta =>
      const TaskConstMeta(debugName: "profile_get", argNames: ["id"]);

  @override
  Future<List<ProfileDto>> crateApiProfileProfileList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_profile_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiProfileProfileListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileListConstMeta =>
      const TaskConstMeta(debugName: "profile_list", argNames: []);

  @override
  Future<List<String>> crateApiProfileProfileTest({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiProfileProfileTestConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileTestConstMeta =>
      const TaskConstMeta(debugName: "profile_test", argNames: ["id"]);

  @override
  Future<ProfileDto> crateApiProfileProfileUpdate({
    required String id,
    required String name,
    required String baseUrl,
    String? apiKey,
    required bool isDefault,
    required List<String> enabledModels,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(baseUrl, serializer);
          sse_encode_opt_String(apiKey, serializer);
          sse_encode_bool(isDefault, serializer);
          sse_encode_list_String(enabledModels, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_dto,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiProfileProfileUpdateConstMeta,
        argValues: [id, name, baseUrl, apiKey, isDefault, enabledModels],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProfileProfileUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "profile_update",
        argNames: [
          "id",
          "name",
          "baseUrl",
          "apiKey",
          "isDefault",
          "enabledModels",
        ],
      );

  @override
  Future<String?> crateApiSettingsSettingsGet({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSettingsSettingsGetConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSettingsGetConstMeta =>
      const TaskConstMeta(debugName: "settings_get", argNames: ["key"]);

  @override
  Future<void> crateApiSettingsSettingsSet({
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSettingsSettingsSetConstMeta,
        argValues: [key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSettingsSetConstMeta =>
      const TaskConstMeta(
        debugName: "settings_set",
        argNames: ["key", "value"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ChatEventDto> dco_decode_StreamSink_chat_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return BridgeError(field0: dco_decode_String(arr[0]));
  }

  @protected
  ChatEventDto dco_decode_chat_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ChatEventDto_Delta(text: dco_decode_String(raw[1]));
      case 1:
        return ChatEventDto_ReasoningDelta(text: dco_decode_String(raw[1]));
      case 2:
        return ChatEventDto_Usage(
          input: dco_decode_u_64(raw[1]),
          output: dco_decode_u_64(raw[2]),
        );
      case 3:
        return ChatEventDto_Done();
      case 4:
        return ChatEventDto_Error(
          code: dco_decode_String(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ConversationDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      profileId: dco_decode_opt_String(arr[2]),
      modelId: dco_decode_opt_String(arr[3]),
      params: dco_decode_String(arr[4]),
      pinned: dco_decode_bool(arr[5]),
      archived: dco_decode_bool(arr[6]),
      updatedAt: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImageInput dco_decode_image_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ImageInput(
      mime: dco_decode_String(arr[0]),
      data: dco_decode_String(arr[1]),
      filePath: dco_decode_String(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conversation_dto).toList();
  }

  @protected
  List<ImageInput> dco_decode_list_image_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_image_input).toList();
  }

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProfileDto> dco_decode_list_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile_dto).toList();
  }

  @protected
  MessageDto dco_decode_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MessageDto(
      id: dco_decode_String(arr[0]),
      role: dco_decode_String(arr[1]),
      text: dco_decode_String(arr[2]),
      images: dco_decode_list_String(arr[3]),
      model: dco_decode_opt_String(arr[4]),
      status: dco_decode_String(arr[5]),
      error: dco_decode_opt_String(arr[6]),
      tokensIn: dco_decode_opt_box_autoadd_i_64(arr[7]),
      tokensOut: dco_decode_opt_box_autoadd_i_64(arr[8]),
      createdAt: dco_decode_i_64(arr[9]),
      rowid: dco_decode_i_64(arr[10]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ProfileDto dco_decode_profile_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ProfileDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      providerType: dco_decode_String(arr[2]),
      baseUrl: dco_decode_String(arr[3]),
      isDefault: dco_decode_bool(arr[4]),
      enabledModels: dco_decode_list_String(arr[5]),
      createdAt: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ChatEventDto> sse_decode_StreamSink_chat_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    return BridgeError(field0: var_field0);
  }

  @protected
  ChatEventDto sse_decode_chat_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return ChatEventDto_Delta(text: var_text);
      case 1:
        var var_text = sse_decode_String(deserializer);
        return ChatEventDto_ReasoningDelta(text: var_text);
      case 2:
        var var_input = sse_decode_u_64(deserializer);
        var var_output = sse_decode_u_64(deserializer);
        return ChatEventDto_Usage(input: var_input, output: var_output);
      case 3:
        return ChatEventDto_Done();
      case 4:
        var var_code = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return ChatEventDto_Error(code: var_code, message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_profileId = sse_decode_opt_String(deserializer);
    var var_modelId = sse_decode_opt_String(deserializer);
    var var_params = sse_decode_String(deserializer);
    var var_pinned = sse_decode_bool(deserializer);
    var var_archived = sse_decode_bool(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return ConversationDto(
      id: var_id,
      title: var_title,
      profileId: var_profileId,
      modelId: var_modelId,
      params: var_params,
      pinned: var_pinned,
      archived: var_archived,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImageInput sse_decode_image_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mime = sse_decode_String(deserializer);
    var var_data = sse_decode_String(deserializer);
    var var_filePath = sse_decode_String(deserializer);
    return ImageInput(mime: var_mime, data: var_data, filePath: var_filePath);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversationDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ImageInput> sse_decode_list_image_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ImageInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_image_input(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProfileDto> sse_decode_list_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProfileDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_images = sse_decode_list_String(deserializer);
    var var_model = sse_decode_opt_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_tokensIn = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_tokensOut = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_rowid = sse_decode_i_64(deserializer);
    return MessageDto(
      id: var_id,
      role: var_role,
      text: var_text,
      images: var_images,
      model: var_model,
      status: var_status,
      error: var_error,
      tokensIn: var_tokensIn,
      tokensOut: var_tokensOut,
      createdAt: var_createdAt,
      rowid: var_rowid,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileDto sse_decode_profile_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_providerType = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_isDefault = sse_decode_bool(deserializer);
    var var_enabledModels = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return ProfileDto(
      id: var_id,
      name: var_name,
      providerType: var_providerType,
      baseUrl: var_baseUrl,
      isDefault: var_isDefault,
      enabledModels: var_enabledModels,
      createdAt: var_createdAt,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_chat_event_dto_Sse(
    RustStreamSink<ChatEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.field0, serializer);
  }

  @protected
  void sse_encode_chat_event_dto(ChatEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ChatEventDto_Delta(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
      case ChatEventDto_ReasoningDelta(text: final text):
        sse_encode_i_32(1, serializer);
        sse_encode_String(text, serializer);
      case ChatEventDto_Usage(input: final input, output: final output):
        sse_encode_i_32(2, serializer);
        sse_encode_u_64(input, serializer);
        sse_encode_u_64(output, serializer);
      case ChatEventDto_Done():
        sse_encode_i_32(3, serializer);
      case ChatEventDto_Error(code: final code, message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(code, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.profileId, serializer);
    sse_encode_opt_String(self.modelId, serializer);
    sse_encode_String(self.params, serializer);
    sse_encode_bool(self.pinned, serializer);
    sse_encode_bool(self.archived, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_image_input(ImageInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mime, serializer);
    sse_encode_String(self.data, serializer);
    sse_encode_String(self.filePath, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation_dto(
    List<ConversationDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_image_input(
    List<ImageInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_image_input(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile_dto(
    List<ProfileDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_String(self.images, serializer);
    sse_encode_opt_String(self.model, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_opt_box_autoadd_i_64(self.tokensIn, serializer);
    sse_encode_opt_box_autoadd_i_64(self.tokensOut, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.rowid, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_dto(ProfileDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.providerType, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_bool(self.isDefault, serializer);
    sse_encode_list_String(self.enabledModels, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
