// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'chat.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `auto_title`, `combine_system`, `drive_chat`, `spawn_chat`, `summarize`, `to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 发送新消息并流式回推（user_text 为 None 时按现有历史重发）。
Stream<ChatEventDto> chatSend({
  required String chatId,
  required String conversationId,
  String? userText,
}) => RustLib.instance.api.crateApiChatChatSend(
  chatId: chatId,
  conversationId: conversationId,
  userText: userText,
);

/// 重新生成：删除最后一条 assistant 消息后重发。
Stream<ChatEventDto> chatRegenerate({
  required String chatId,
  required String conversationId,
}) => RustLib.instance.api.crateApiChatChatRegenerate(
  chatId: chatId,
  conversationId: conversationId,
);

/// 编辑重发：改 user 消息内容，删除其后续，重发。
Stream<ChatEventDto> chatEditResend({
  required String chatId,
  required String conversationId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiChatChatEditResend(
  chatId: chatId,
  conversationId: conversationId,
  messageId: messageId,
  newText: newText,
);

/// 中止进行中的对话（无此 chat_id 时静默忽略）。
Future<void> chatCancel({required String chatId}) =>
    RustLib.instance.api.crateApiChatChatCancel(chatId: chatId);

@freezed
sealed class ChatEventDto with _$ChatEventDto {
  const ChatEventDto._();

  const factory ChatEventDto.delta({required String text}) = ChatEventDto_Delta;
  const factory ChatEventDto.reasoningDelta({required String text}) =
      ChatEventDto_ReasoningDelta;
  const factory ChatEventDto.usage({
    required BigInt input,
    required BigInt output,
  }) = ChatEventDto_Usage;
  const factory ChatEventDto.done() = ChatEventDto_Done;
  const factory ChatEventDto.error({
    required String code,
    required String message,
  }) = ChatEventDto_Error;
}
