// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'chat.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `combine_system`, `parse_role`, `run_chat_inner`, `run_chat`, `summarize`, `to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 发起流式对话。事件通过 sink 回推；流被 Dart 侧取消时任务随之结束。
Stream<ChatEventDto> chatSend({
  required String chatId,
  required String profileId,
  required String model,
  required List<ChatMessageDto> messages,
  String? system,
  double? temperature,
  double? topP,
  int? maxTokens,
  int? contextWindow,
}) => RustLib.instance.api.crateApiChatChatSend(
  chatId: chatId,
  profileId: profileId,
  model: model,
  messages: messages,
  system: system,
  temperature: temperature,
  topP: topP,
  maxTokens: maxTokens,
  contextWindow: contextWindow,
);

/// 中止进行中的对话（无此 chat_id 时静默忽略）。
Future<void> chatCancel({required String chatId}) =>
    RustLib.instance.api.crateApiChatChatCancel(chatId: chatId);

@freezed
sealed class ChatEventDto with _$ChatEventDto {
  const ChatEventDto._();

  const factory ChatEventDto.delta({required String text}) = ChatEventDto_Delta;
  const factory ChatEventDto.reasoningDelta({required String text}) =
      ChatEventDto_ReasoningDelta;
  const factory ChatEventDto.usage({
    required BigInt input,
    required BigInt output,
  }) = ChatEventDto_Usage;
  const factory ChatEventDto.done() = ChatEventDto_Done;
  const factory ChatEventDto.error({
    required String code,
    required String message,
  }) = ChatEventDto_Error;
}

class ChatMessageDto {
  final String role;
  final String content;

  const ChatMessageDto({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}
