// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean`, `to_dto`

Future<ConversationDto> conversationCreate({
  String? profileId,
  String? modelId,
}) => RustLib.instance.api.crateApiConversationConversationCreate(
  profileId: profileId,
  modelId: modelId,
);

Future<List<ConversationDto>> conversationList() =>
    RustLib.instance.api.crateApiConversationConversationList();

Future<ConversationDto> conversationGet({required String id}) =>
    RustLib.instance.api.crateApiConversationConversationGet(id: id);

/// title/pinned/archived 传 None 表示不动。
Future<ConversationDto> conversationUpdateMeta({
  required String id,
  String? title,
  bool? pinned,
  bool? archived,
}) => RustLib.instance.api.crateApiConversationConversationUpdateMeta(
  id: id,
  title: title,
  pinned: pinned,
  archived: archived,
);

Future<ConversationDto> conversationSetModel({
  required String id,
  required String profileId,
  required String modelId,
}) => RustLib.instance.api.crateApiConversationConversationSetModel(
  id: id,
  profileId: profileId,
  modelId: modelId,
);

Future<void> conversationDelete({required String id}) =>
    RustLib.instance.api.crateApiConversationConversationDelete(id: id);

class ConversationDto {
  final String id;
  final String title;
  final String? profileId;
  final String? modelId;
  final String params;
  final bool pinned;
  final bool archived;
  final PlatformInt64 updatedAt;

  const ConversationDto({
    required this.id,
    required this.title,
    this.profileId,
    this.modelId,
    required this.params,
    required this.pinned,
    required this.archived,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      profileId.hashCode ^
      modelId.hashCode ^
      params.hashCode ^
      pinned.hashCode ^
      archived.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          profileId == other.profileId &&
          modelId == other.modelId &&
          params == other.params &&
          pinned == other.pinned &&
          archived == other.archived &&
          updatedAt == other.updatedAt;
}
