// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// M1 脚手架验证：把输入经 Rust 核心（EchoProvider）流式回显给 Dart。
Stream<String> echoStream({required String input}) =>
    RustLib.instance.api.crateApiEchoEchoStream(input: input);
