// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `storage`

/// 启动时调用：注入主密钥（base64 的 32B）并打开数据库。
/// db_path 由 Dart 侧 path_provider 提供。
Future<void> initCore({required String dbPath, required String masterKeyB64}) =>
    RustLib.instance.api.crateApiLifecycleInitCore(
      dbPath: dbPath,
      masterKeyB64: masterKeyB64,
    );
