// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_dto`

Future<List<MessageDto>> messageList({required String conversationId}) =>
    RustLib.instance.api.crateApiMessageMessageList(
      conversationId: conversationId,
    );

Future<void> messageDelete({required String id}) =>
    RustLib.instance.api.crateApiMessageMessageDelete(id: id);

class MessageDto {
  final String id;
  final String role;

  /// 本期为纯文本（content parts 中的 text）。
  final String content;
  final String? model;
  final String status;
  final String? error;
  final PlatformInt64? tokensIn;
  final PlatformInt64? tokensOut;
  final PlatformInt64 createdAt;

  const MessageDto({
    required this.id,
    required this.role,
    required this.content,
    this.model,
    required this.status,
    this.error,
    this.tokensIn,
    this.tokensOut,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      role.hashCode ^
      content.hashCode ^
      model.hashCode ^
      status.hashCode ^
      error.hashCode ^
      tokensIn.hashCode ^
      tokensOut.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          role == other.role &&
          content == other.content &&
          model == other.model &&
          status == other.status &&
          error == other.error &&
          tokensIn == other.tokensIn &&
          tokensOut == other.tokensOut &&
          createdAt == other.createdAt;
}
