// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean`, `parse_content`, `to_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ImagePart`

Future<List<MessageDto>> messageList({required String conversationId}) =>
    RustLib.instance.api.crateApiMessageMessageList(
      conversationId: conversationId,
    );

/// 分页拉取：before 游标（created_at, rowid）之前的一页；None 取最新一页。
Future<List<MessageDto>> messageListPage({
  required String conversationId,
  PlatformInt64? beforeCreatedAt,
  PlatformInt64? beforeRowid,
  required int limit,
}) => RustLib.instance.api.crateApiMessageMessageListPage(
  conversationId: conversationId,
  beforeCreatedAt: beforeCreatedAt,
  beforeRowid: beforeRowid,
  limit: limit,
);

Future<void> messageDelete({required String id}) =>
    RustLib.instance.api.crateApiMessageMessageDelete(id: id);

class MessageDto {
  final String id;
  final String role;

  /// 文本部分（多段 text 以空行拼接）。
  final String text;

  /// 图片相对路径（app_dir/files/...）。
  final List<String> images;
  final String? model;
  final String status;
  final String? error;
  final PlatformInt64? tokensIn;
  final PlatformInt64? tokensOut;
  final PlatformInt64 createdAt;

  /// SQLite 行号，分页游标用（与 created_at 组成 (created_at, rowid)）。
  final PlatformInt64 rowid;

  const MessageDto({
    required this.id,
    required this.role,
    required this.text,
    required this.images,
    this.model,
    required this.status,
    this.error,
    this.tokensIn,
    this.tokensOut,
    required this.createdAt,
    required this.rowid,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      role.hashCode ^
      text.hashCode ^
      images.hashCode ^
      model.hashCode ^
      status.hashCode ^
      error.hashCode ^
      tokensIn.hashCode ^
      tokensOut.hashCode ^
      createdAt.hashCode ^
      rowid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          role == other.role &&
          text == other.text &&
          images == other.images &&
          model == other.model &&
          status == other.status &&
          error == other.error &&
          tokensIn == other.tokensIn &&
          tokensOut == other.tokensOut &&
          createdAt == other.createdAt &&
          rowid == other.rowid;
}
