// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean`, `to_dto`

Future<ProfileDto> profileCreate({
  required String name,
  required String providerType,
  required String baseUrl,
  required String apiKey,
  required bool isDefault,
}) => RustLib.instance.api.crateApiProfileProfileCreate(
  name: name,
  providerType: providerType,
  baseUrl: baseUrl,
  apiKey: apiKey,
  isDefault: isDefault,
);

Future<List<ProfileDto>> profileList() =>
    RustLib.instance.api.crateApiProfileProfileList();

Future<ProfileDto> profileGet({required String id}) =>
    RustLib.instance.api.crateApiProfileProfileGet(id: id);

/// api_key 传 None 表示不改密钥。
Future<ProfileDto> profileUpdate({
  required String id,
  required String name,
  required String baseUrl,
  String? apiKey,
  required bool isDefault,
  required List<String> enabledModels,
}) => RustLib.instance.api.crateApiProfileProfileUpdate(
  id: id,
  name: name,
  baseUrl: baseUrl,
  apiKey: apiKey,
  isDefault: isDefault,
  enabledModels: enabledModels,
);

Future<void> profileDelete({required String id}) =>
    RustLib.instance.api.crateApiProfileProfileDelete(id: id);

/// 连通性测试：解密 Key → 构造 Provider → 拉取模型列表。
Future<List<String>> profileTest({required String id}) =>
    RustLib.instance.api.crateApiProfileProfileTest(id: id);

/// 传给 Dart 的 Profile 视图（不含密钥密文）。
class ProfileDto {
  final String id;
  final String name;
  final String providerType;
  final String baseUrl;
  final bool isDefault;
  final List<String> enabledModels;
  final PlatformInt64 createdAt;

  const ProfileDto({
    required this.id,
    required this.name,
    required this.providerType,
    required this.baseUrl,
    required this.isDefault,
    required this.enabledModels,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      providerType.hashCode ^
      baseUrl.hashCode ^
      isDefault.hashCode ^
      enabledModels.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          providerType == other.providerType &&
          baseUrl == other.baseUrl &&
          isDefault == other.isDefault &&
          enabledModels == other.enabledModels &&
          createdAt == other.createdAt;
}
