// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean`

Future<String?> settingsGet({required String key}) =>
    RustLib.instance.api.crateApiSettingsSettingsGet(key: key);

Future<void> settingsSet({required String key, required String value}) =>
    RustLib.instance.api.crateApiSettingsSettingsSet(key: key, value: value);
